[paths]
data_dir = "data"
models_dir = "models"
food_data = "data/food_data.csv"
exercise_data = "data/exercise_data.csv"
food_model = "models/food_model.pkl"
exercise_model = "models/exercise_model.pkl"